create database Grocery;
use grocery;


select * from categories;
select * from customers;
select * from orderdetails;
select * from orders;
select * from products;
select * from store_employees;

select * from suppliers;

-- 1️. Customer Insights

-- ● How many unique customers have placed orders?
select count(CustomerID) from customers;       



-- ● Which customers have placed the highest number of orders?
select * from orderdetails   
order by Quantity desc;
select c.name,od.Quantity from customers c
join orders o
on c.CustomerID = o.CustomerID
join orderdetails od
on o.OrderID = od.OrderID
having Quantity = 5;
-- ● What is the total and average purchase value per customer?
select c.CustomerID,c.Name,sum(od.TotalPrice) as Total, avg(od.TotalPrice) as Average from customers c   
join orders o 
on c.CustomerID = o.CustomerID
join orderdetails od
on o.OrderID = od.OrderID
group by c.CustomerID,c.Name
order by customerID asc;
-- ● Who are the top 5 customers by total purchase amount?        
select c.Name,sum(od.TotalPrice) as TotalPurchase from customers c
join orders o
on c.CustomerID = o.CustomerID
join orderdetails od
on o.OrderID = od.OrderID
group by c.Name
order by TotalPurchase desc
limit 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- ● How many products exist in each category?               
select c.CategoryID,c.CategoryName,count(productID) as product_count from categories c
join products p
on c.CategoryID = p.CategoryID
group by c.CategoryID,c.CategoryName;

-- ● What is the average price of products by category?
select c.CategoryID,CategoryName,avg(price) as Average from categories c
join products p
on c.CategoryID=p.CategoryID
group by c.CategoryID,CategoryName;
-- ● Which products have the highest total sales volume (by quantity)?
select p.productID,p.Name,sum(od.Quantity) from products p
join orderdetails od
on p.ProductID = od.ProductID
group by p.productID,p.Name
limit 1;
-- ● What is the total revenue generated by each product?   ##1
select p.ProductID,p.Name,sum(od.TotalPrice) from products p
join orderdetails od 
on p.ProductID = od.ProductID
group by p.ProductID,p.Name
order by productID asc;



-- ● How do product sales vary by category and supplier?
select c.CategoryID,c.CategoryName,s.SupplierID,s.SupplierName, 
sum(od.TotalPrice) as Total from orderdetails od
join products p
on od.ProductID = p.ProductID
join categories c
on p.CategoryID = c.CategoryID
join suppliers s
on s.supplierID = p.supplierID
group by  c.CategoryID,c.CategoryName,s.SupplierID,s.SupplierName
order by Total desc;
-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- ● How many orders have been placed in total?      
SELECT COUNT(*) AS total_orders FROM orders;



-- ● What is the average value per order?             
select orderID,avg(TotalPrice) as AVG_Value from orderdetails
group by orderID;

-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- ● How many suppliers are there in the database?
select count(SupplierID) from suppliers;   


##● Which supplier provides the most products?           
select s.supplierName,count(p.ProductID) as totalproduct
from suppliers s
join products p 
on s.SupplierID = p.SupplierID
group by s.supplierName
order  by totalproduct desc
limit 1;
-- ● What is the average price of products from each supplier?
select p.Name,s.SupplierName,avg(p.Price) from products p
join suppliers s
group by p.Name,s.SupplierName;
-- ● Which suppliers contribute the most to total product sales (by revenue)?

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- ● How many employees have processed orders?
select count(distinct EmployeeID) as Total_Employees from orders;  


-- ● Which employees have handled the most orders?
select se.name,count(o.orderID) as total_order from store_employees se   
join orders o
on o.EmployeeID = se.EmployeeID
group by se.name
order by total_order desc
limit 1;

-- ● What is the total sales value processed by each employee?
select se.Name, sum(od.TotalPrice) as total_price from store_employees se
join orders o
on se.EmployeeID = o.EmployeeID
join orderdetails od
on o.OrderID = od.OrderID
group by se.Name;
-- ● What is the average order value handled per employee?         
select se.name, avg(od.TotalPrice) as order_value from store_employees se
join orders o
on se.EmployeeID = o.EmployeeID
join orderdetails od 
on o.OrderID = od.OrderID
group by se.name;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- ● What is the relationship between quantity ordered and total price?
select quantity,priceEach,(quantity* priceEach) as Total_price from orderdetails;

-- ● What is the average quantity ordered per product?
select ProductId, Avg(Quantity) as avg_quantity from orderdetails
group by ProductId;
-- ● How does the unit price vary across products and orders?
select ProductID, 
min(PriceEach) as min_price,
max(PriceEach) as max_price,
avg(PriceEach) as avg_price
from orderdetails
group by ProductID;

